{
 "title": "Nistagram Microservices",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Microservice Requests / 10min",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nistagram_profile_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_auth_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_post_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_postreaction_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_connection_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_monitoring_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_notification_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_campaign_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    }
   ]
  },
  {
   "title": "Endpoint Timing Average by Status / 30min",
   "type": "bargauge",
   "gridPos": { "h": 62, "w": 24, "x": 0, "y": 15 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(nistagram_auth_http_response_time_seconds_sum[30m])",
     "legendFormat": "{{instance}} | {{path}} : {{status}}"
    },
    {
     "expr": "rate(nistagram_profile_http_response_time_seconds_sum[30m])",
     "legendFormat": "{{instance}} | {{path}} : {{status}}"
    },
    {
     "expr": "rate(nistagram_post_http_response_time_seconds_sum[30m])",
     "legendFormat": "{{instance}} | {{path}} : {{status}}"
    },
    {
     "expr": "rate(nistagram_postreaction_http_response_time_seconds_sum[30m])",
     "legendFormat": "{{instance}} | {{path}} : {{status}}"
    },
    {
     "expr": "rate(nistagram_connection_http_response_time_seconds_sum[30m])",
     "legendFormat": "{{instance}} | {{path}} : {{status}}"
    },
    {
     "expr": "rate(nistagram_notification_http_response_time_seconds_sum[30m])",
     "legendFormat": "{{instance}} | {{path}} : {{status}}"
    },
    {
     "expr": "rate(nistagram_campaign_http_response_time_seconds_sum[30m])",
     "legendFormat": "{{instance}} | {{path}} : {{status}}"
    },
    {
     "expr": "rate(nistagram_monitoring_http_response_time_seconds_sum[30m])",
     "legendFormat": "{{instance}} | {{path}} : {{status}}"
    }
   ]
  },
  {
   "title": "Auth MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 77 },
   "targets": [
    {
     "expr": "rate(nistagram_auth_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "ERROR Auth MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 77 },
   "targets": [
    {
     "expr": "rate(nistagram_auth_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "Profile MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 89 },
   "targets": [
    {
     "expr": "rate(nistagram_profile_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "ERROR Profile MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 89 },
   "targets": [
    {
     "expr": "rate(nistagram_profile_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "Post MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 101 },
   "targets": [
    {
     "expr": "rate(nistagram_post_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "ERROR Post MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 101 },
   "targets": [
    {
     "expr": "rate(nistagram_post_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "PostReaction MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 113 },
   "targets": [
    {
     "expr": "rate(nistagram_postreaction_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "ERROR PostReaction MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 113 },
   "targets": [
    {
     "expr": "rate(nistagram_postreaction_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "Connection MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "expr": "rate(nistagram_connection_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "ERROR Connection MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "expr": "rate(nistagram_connection_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "Notification MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 137 },
   "targets": [
    {
     "expr": "rate(nistagram_notification_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "ERROR Notification MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 137 },
   "targets": [
    {
     "expr": "rate(nistagram_notification_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "Campaign MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 149 },
   "targets": [
    {
     "expr": "rate(nistagram_campaign_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "ERROR Caampaign MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 149 },
   "targets": [
    {
     "expr": "rate(nistagram_campaign_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "Monitoring MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 161 },
   "targets": [
    {
     "expr": "rate(nistagram_monitoring_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "ERROR Monitoring MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 161 },
   "targets": [
    {
     "expr": "rate(nistagram_monitoring_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "Cross Microservice Communication",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 173 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, path, job) (rate(nistagram_http_requests_initiators{initiator=~\"[a-z]*\"}[30m]))",
     "legendFormat": "{{initiator}}"
    }
   ]
  },
  {
   "title": "Agent API Access",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 183 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, path, job) (rate(nistagram_http_requests_initiators{initiator=~\"API_[0-9]*\"}[30m]))",
     "legendFormat": "{{initiator}}"
    }
   ]
  },
  {
   "title": "Nistagram User Access / 30min",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 193 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum without (instance, path, job) (rate(nistagram_http_requests_initiators{initiator=~\"[0-9]*\"}[30m]))",
     "legendFormat": "{{initiator}}"
    }
   ]
  }
 ]
}