{
 "title": "Nistagram Microservices",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Microservice Requests / 10min",
   "type": "timeseries",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(nistagram_profile_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_auth_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_post_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_postreaction_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_connection_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_monitoring_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_notification_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    },
    {
     "expr": "rate(nistagram_campaign_http_requests_total[10m])",
     "legendFormat": "{{instance}}|{{path}}"
    }
   ]
  },
  {
   "title": "profile err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "rate(nistagram_profile_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "auth err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "targets": [
    {
     "expr": "rate(nistagram_auth_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "post err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "targets": [
    {
     "expr": "rate(nistagram_post_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "postreaction err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "expr": "rate(nistagram_postreaction_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "connection err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "rate(nistagram_connection_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "notification err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "expr": "rate(nistagram_notification_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "campaign err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "targets": [
    {
     "expr": "rate(nistagram_campaign_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "monitoring err",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "expr": "rate(nistagram_monitoring_http_response_status{status!=\"201\", status!=\"200\"}[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "Auth MS endpoint stat / 5 min",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "expr": "rate(nistagram_auth_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "profile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
   "targets": [
    {
     "expr": "rate(nistagram_profile_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "post",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "rate(nistagram_post_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "postreaction",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(nistagram_postreaction_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "connection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
   "targets": [
    {
     "expr": "rate(nistagram_connection_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "notification",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 63 },
   "targets": [
    {
     "expr": "rate(nistagram_notification_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "campaign",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 71 },
   "targets": [
    {
     "expr": "rate(nistagram_campaign_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  },
  {
   "title": "monitoring",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 71 },
   "targets": [
    {
     "expr": "rate(nistagram_monitoring_http_response_status[5m])",
     "legendFormat": "{{status}}<={{path}}"
    }
   ]
  }
 ]
}